table primary_locations
	lineageTag: 2b29b097-51f9-4671-bb73-0bdc4c7eeff1

	column location_name
		dataType: string
		lineageTag: 7495ff65-adfe-4429-8c50-f8ee27ae6f31
		summarizeBy: none
		sourceColumn: location_name

		annotation SummarizationSetBy = Automatic

	column created_at_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: d1cdadd8-7001-42ad-ad94-537ed3e7bc3d
		summarizeBy: none
		sourceColumn: created_at_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition primary_locations = m
		mode: import
		source =
				let
				    Source = inventory_changes,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"location_name", "created_at_date"}),
				    #"Appended Query" = Table.Combine({#"Removed Other Columns", item_locations_manual}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Appended Query",{"location_name", "created_at_date"}),
				    #"Sorted Rows" = Table.Buffer(Table.Sort(#"Removed Other Columns1",{{"created_at_date", Order.Descending}})),
				    #"Removed Duplicates" = Table.Distinct(#"Sorted Rows", {"location_name"})
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

